# -*- coding: utf-8 -*-
"""AI: MLDimensionality (Refrain Prediction).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/196eCmE8gB_hsTuVMt_KAPUqivobqOrwg
"""

# Imports
from sklearn.model_selection import train_test_split
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis 
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Data
dataFile = "//content//drive//MyDrive//Coding//Personal Projects//1: Artificial Intelligence//Resources//RefrainPrediction.csv"
data = pd.read_csv(dataFile)
dataset = data.values.tolist()
X = []
Y = []

for row in dataset:
  musicData = []
  for column in range(0,len(row)):
    if column == 26: # last column = music genre type
      Y.append(str(row[column]))
    else:
      musicData.append(str(row[column]))
  X.append(musicData)

scaler = StandardScaler()
scaler.fit(X)
StandardScaler()
scaler.transform(X)

# Model
model = QuadraticDiscriminantAnalysis()
model.fit(X, Y)
crossValidation = RepeatedStratifiedKFold(n_splits = 100, n_repeats = 100, random_state = 1)
scores = cross_val_score(model, X, Y, scoring = 'accuracy', cv = crossValidation, n_jobs = -1)
print(np.mean(scores))